---
language: python
dist: xenial

cache:
  pip: true
  directories:
    - "$HOME/.cache/pip"

addons:
  apt:
    packages:
      - libspatialindex-dev

python:
  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"

install:
  - pip install --upgrade pip
  - pip install -r ci/requirements.txt
  - pip install .

script:
  - flake8 --exit-zero
  - pytest -v

notifications:
  email: false
