---
language: python
dist: xenial

cache:
  pip: true
  directories:
    - "$HOME/.cache/pip"

addons:
  apt:
    packages:
      - gcc
      - gfortran
      - libspatialindex-dev

python:
  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"

before_install:
  - ./ci/mf2005/install.sh
  - ./ci/mfnwt/install.sh

install:
  - pip install --upgrade pip
  - pip install -r ci/requirements.txt
  - pip install .

script:
  - flake8 --exit-zero
  - pytest -v

notifications:
  email: false
